### PR TITLE
Implement xml.Unmarshaller for SOAPBody

### LINKED ISSUE #37: Error unmarshalling responses from VirtualBox vboxwebsrv
I'm trying to use `gowsdl` to generate code to interface with VirtualBox's `vboxwebsrv` SOAP service, but I'm running into namespace issues.

My test code can be found here: https://github.com/md5/gowsdl-vboxwebsrv-test, including the generated service code, but the stripped-down test file looks like this:

```golang
package main

import (
	"./vboxwebsrv"

	"log"
	"os"
)

func main() {
	var addr string

	if len(os.Args) < 2 {
		addr = "http://127.0.0.1:18083"
	} else {
		addr = os.Args[1]
	}

	svc := vboxwebsrv.NewVboxPortType(addr, false, nil)
	vbox, err := svc.IWebsessionManagerlogon(&vboxwebsrv.IWebsessionManagerlogon{})
	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("returnval=%s\n", vbox.Returnval)
}
```

When I run it with `go run test.go`, I get the following error:

```console
$ go run test.go http://192.168.99.1:18083
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vbox="http://www.virtualbox.org/"><SOAP-ENV:Body><vbox:IWebsessionManager_logonResponse><returnval>954ddf3e6d57d58b-000000000000000a</returnval></vbox:IWebsessionManager_logonResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
2015/09/10 08:42:18 expected element <IWebsessionManager_logonResponse> in name space http://www.virtualbox.org/ but have vbox
exit status 1
```

After looking through the `gowsdl` code, it appears that the issue is that the `<vbox:IWebsessionManager_logonResponse><returnval>954ddf3e6d57d58b-000000000000000a</returnval></vbox:IWebsessionManager_logonResponse>` body is being unmarshalled by an instance of `xml.Decoder` that no longer has the `xmlns:vbox="http://www.virtualbox.org/"` namespace mapping.

Any advice you can provide here would be appreciated. It seems like `gowsdl` might need to use something lower level than `xml.Unmarshal` to allow the same `xml.Decoder` to decode the entire SOAP payload and maintain its namespace mappings.

Here's my Go version:

```console
$ go version 
go version go1.5 darwin/amd64
```

### PR DESCRIPTION
**Pull request by md5**
I'm opening this PR to get some feedback since I'm very new at writing Go code.

These changes allow unmarshalling and marshalling to happen in a single pass, which allows a broader range of SOAP responses to be parsed. In particular, it handles the case where the `xmlns` used on the `<SOAP-ENV:Body>` entries is declared on a parent element instead of on the entry itself.

I would have liked to add some tests here, but I'm not clear on how to structure tests that use the generated code from `soap_tmpl.go`. I'm happy to add some tests if someone can give me some pointers on how to do so. I was able to run `make test`, so I at least don't think I broke any of the existing tests.

Fixes #37

### CODE REVIEW

**Comment by md5** [comment]
BTW, I used my modified version of `gowsdl` to start working on a client for VirtualBox here: https://github.com/appropriate/go-virtualboxclient

**Comment by c4milo** [comment]
This looks good to me @md5. Thank you!

**Comment by md5** [comment]
Thanks @c4milo :+1: 

I'm still willing to add some tests in this area, assuming I can get a start in the right direction. Perhaps @sanbornm might have some ideas here.

**Comment by sanbornm** [comment]
@md5 I think we need to figure out how to check if our generated code would compile or not.  We are currently testing it by running it through go fmt (https://github.com/hooklift/gowsdl/blob/master/gowsdl_test.go#L56) which catches a lot of errors but I am not sure it checks everything.

**Pull request merged**
