### PR TITLE
Add additional err handling to SOAP template

### PR DESCRIPTION
**Pull request by md5**
These changes were proposed for the generated output file over at https://github.com/appropriate/go-virtualboxclient/pull/1 and I thought they seemed reasonable.

Please take a look! :+1:

### CODE REVIEW

**Comment by md5** [comment]
Thanks @c4milo!

**Comment by c4milo** [comment]
No, thank you!

**Comment by md5** [comment]
To give credit where credit is due, @clintonskitson was the source of these changes. :+1:

**Comment by md5** [comment]
@c4milo Are you planning on cutting a new release that includes changes since `v0.2.0` any time soon?

**Comment by c4milo** [comment]
@md5 a new release will be up shortly.

**Comment by c4milo** [comment]
@md5 landed in v0.2.1

**Comment by md5** [comment]
Thanks @c4milo. You rock! :metal:

**Comment by md5** [comment]
I ended up making a Homebrew tap for `gowsdl` to help out us OS X users: https://github.com/appropriate/homebrew-gowsdl

It can be used like so:

```console
$ brew tap appropriate/gowsdl
$ brew install gowsdl
```

If there's any interest, it would probably be pretty uncontroversial to add it to Homebrew itself. I'd also be happy to share ownership of the repo and/or transfer it under `hooklift`.

**Comment by c4milo** [comment]
I don't have strong feelings against it.

**Comment by md5** [comment]
I've opened a PR to add `gowsdl` to Homebrew proper: https://github.com/Homebrew/homebrew/pull/47282

**Comment by c4milo** [comment]
:+1:

**Pull request merged**
