### PR TITLE
Removed extra line break on element loop so go fmt will "work"

### PR DESCRIPTION
**Pull request by sanbornm**

### CODE REVIEW

**Comment by sanbornm** [comment]
Sorry for the large pull request, I wasn't sure how to break these up into smaller PRs.

**Comment by c4milo** [comment]
@sanbornm How about also moving the code inside `generator` to the root and the cli (main) to `cmd` just to be more idiomatic.

**Comment by sanbornm** [comment]
@c4milo I think that is a great idea.  I will make an update.  Do the rest of these commits make sense?

**Comment by c4milo** [comment]
Yes, they are fine.

**Comment by sanbornm** [comment]
I modified the readme to include a link to the release section as we should probably provide a binary release.  Can you add a release here:

https://github.com/hooklift/gowsdl/releases

**Comment by c4milo** [comment]
Yes, as soon as I can get my hands on a computer. Thanks Mark!

**Comment by sanbornm** [comment]
I added a test to check all WSDL files in fixture check against go fmt, do you know of a more strict test or a way to check to see if it would compile?

**Comment by md5** [comment]
Whoa! I didn't expect such a huge diff based on that title :astonished:

**Comment by sanbornm** [comment]
Sorry about that, I thought I could do a separate pull request for each commit.  Next time I will use branches.

**Comment by md5** [comment]
No worries. The changes look good! :+1:

**Pull request merged**
