### PR TITLE
Less restrictive checks in MTOMDecoder

### PR DESCRIPTION
**Pull request by giovanni-orciuolo**
Makes more MTOM-based services work correctly. Sometimes, some services do not use the exact names in their headers.

### CODE REVIEW

**Comment by c4milo** [comment]
What’s the content type value coming from your service? I believe we should be able to use `strings.HasPrefix` here.

**Comment by giovanni-orciuolo** [comment]
> What’s the content type value coming from your service? I believe we should be able to use `strings.HasPrefix` here.

I get this string:
`Content-Type: application/xop+xml; charset=UTF-8; type="text/xml";`

So I believe we could theoretically use application/xop+xml as a prefix

**Comment by c4milo** [comment]
Right, I have always seen the content type first and extra attributes coming after.

**Comment by c4milo** [comment]
Yep: https://datatracker.ietf.org/doc/html/rfc2045#section-5.1

**Comment by giovanni-orciuolo** [comment]
Alright, so can I make a commit with HasPrefix and merge?

**Comment by c4milo** [comment]
Yes

**Comment by c4milo** [comment]
If we were to do this better, it would be by using a more robust parser: https://pkg.go.dev/mime

**Comment by giovanni-orciuolo** [comment]
Yeah, but I believe the only 2 cases we have at the moment are `application/soap+xml` and `text/xml` in `start-info`. Should more cases arise, we should consider using that library

**Comment by c4milo** [comment]
We also have the one raised in #217

**Comment by c4milo** [comment]
The one coming in the mtom header.

**Comment by giovanni-orciuolo** [comment]
I think we both had the exact same problem and solved it in the same way. The commits do the same thing. You can choose which one your prefer to merge ^^

**Comment by giovanni-orciuolo** [comment]
Can you merge this PR into the base library? I need it in a production environment

**Comment by giovanni-orciuolo** [comment]
I added more comprehensive checks inside the `getBinaryFields` function, in order to account for a vast amount of cases in the XML response (e.g. slices, pointers, etc...) in order to populate the binary fields.

**Pull request merged**
