### PR TITLE
Generate operation methods that take context

### PR DESCRIPTION
**Pull request by iszak**
This will allow setting a deadline per operation invocation as well
as the ability to cancel.

Follow up of https://github.com/hooklift/gowsdl/pull/124 , possibly related https://github.com/hooklift/gowsdl/issues/111

### CODE REVIEW

**Comment by c4milo** [comment]
@iszak, I think we can just leave one method, receiving context and have people just passing context.TODO() or context.Background() if they don't want to do cancellations.

**Comment by iszak** [comment]
@c4milo I'm not sure I understand what you mean. I decided to have two methods, as otherwise it would break backwards compatibility.

**Comment by c4milo** [comment]
@iszak, yes, I misunderstood the intention. That's why I went ahead and merged it. Thanks!

**Comment by iszak** [comment]
@c4milo this was actually broken, can you please review https://github.com/hooklift/gowsdl/pull/133

**Pull request merged**
