### PR TITLE
Wrap WDSL doc tag in multiline comment

### PR DESCRIPTION
**Pull request by notzippy**
Fix for issue #21 Wrap Doc in multiline comment

### CODE REVIEW

**Comment by c4milo** [comment]
@notzippy good catch. Thanks!

**Comment by notzippy** [comment]
@c4milo np, thanks for the package - in my case I will need soap headers, any reason why they were removed (commented out) in this commit ? 
https://github.com/hooklift/gowsdl/commit/8cdcd28bece8d0a3e52995c48cf04d3aaaf9e635#diff-a28674aaa747f6f812524acd398242af
https://github.com/hooklift/gowsdl/blob/master/generator/soap.go#L62

**Comment by c4milo** [comment]
@notzippy they've been never really supported :/

**Comment by c4milo** [comment]
@notzippy it should be difficult to add support for headers, I just haven't found the time to do it. Let me know if you want to give it a stab.

**Pull request merged**
